### ISSUE TITLE
Roboto font is being loaded without HTTPS, causing it to be blocked on Chrome

### ISSUE THREAD

**Issue by brundonsmith** [born2net/studioDashboard#4]
<img width="729" alt="digitalsignage_-_studiodashboard" src="https://cloud.githubusercontent.com/assets/3674979/17668043/31e7417e-62cd-11e6-90ea-3ee218ff56fb.png">

Should be a simple matter of changing 'http' to 'https'

**Comment by born2net** [comment]
tx fixed!!!
