### ISSUE TITLE
Reduce boilerplate for using StoreModel

### ISSUE THREAD

**Issue by bryanrideshark** [born2net/studioDashboard#5]
Love the concepts you've got here, there's a real elegance to the StoreModel.

I was curious, was there any reason you didn't go with an abstract class for StoreModel? I made a fork and modified StoreModel to reduce the amount of boilerplate required for use.

https://github.com/bryanrideshark/studioDashboard/pull/1

Your comments would be appreciated :)

**Comment by born2net** [comment]
while I didn't test it, it does seem cleaner.
when I came up with this model, very little info was available on Angular and patterns with TS, so I welcome updates such as this.

Sean

**Comment by born2net** [comment]
by the way, if you want an even better project built around StoreModel and ngrx see:
https://github.com/born2net/studio-lite
